// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var addInfo, appendNameToCast, appendNamesToArtistBox, currentPos, getArtistInfo, getPics, goToArtist, goToNext, goToPrev, resetPics, setUpBinds, setupPics, updateNextArtistLink;
    currentPos = 0;
    getArtistInfo = function() {
      return $.ajax('artists.json', {
        success: function(data, status, xhr) {
          var artist, bio, i, info, lecture, magazine, name, nickname, radio, website, _i, _len, _results;
          info = data.artists;
          _results = [];
          for (i = _i = 0, _len = info.length; _i < _len; i = ++_i) {
            artist = info[i];
            name = info[i].name;
            nickname = info[i].nickname;
            lecture = info[i].lecture;
            magazine = info[i].magazine;
            radio = info[i].radio;
            bio = info[i].bio;
            website = info[i].website;
            appendNameToCast(name, nickname);
            _results.push(appendNamesToArtistBox(name, nickname, bio, lecture, radio, magazine, website));
          }
          return _results;
        },
        error: function(xhr, status, err) {
          return console.log('fail');
        },
        complete: function(xhr, status) {
          return setUpBinds();
        }
      });
    };
    appendNameToCast = function(name, nickname) {
      var artistName, castList, imageList;
      castList = $('.artist-list ul');
      imageList = $('.artist-images');
      castList.append("<a data-name='" + name + "' href='#' data-pic='" + nickname + "'><li>" + name + "</li></a>");
      imageList.append("<img data-pic='" + nickname + "' class='" + nickname + "' src='//d17vwh530ty7de.cloudfront.net/artist/" + nickname + ".jpg' alt='" + name + "'>");
      return artistName = $('.artist-list ul a');
    };
    appendNamesToArtistBox = function(name, nickname, bio, lecture, radio, magazine, website) {
      $('#artist-info').append("<p class='bio " + nickname + "-bio'>" + bio + "</p>");
      $('#artist-info').append("<div class='links'><ul class='" + nickname + "-links'></ul>");
      if (lecture) {
        $("#artist-info ." + nickname + "-links").append(("<li><a href='" + lecture + "' target='blank'>") + "<img src='//d17vwh530ty7de.cloudfront.net/play.gif' /></a>" + ("<a href='" + lecture + "' target='blank'>Watch Lecture</a></li>"));
      }
      if (radio) {
        $("#artist-info ." + nickname + "-links").append(("<li><a href='" + radio + "' target='blank'>") + "<img src='//d17vwh530ty7de.cloudfront.net/play.gif' /></a>" + ("<a href='" + radio + "' target='blank'>RBMA Radio Show</a></li>"));
      }
      if (magazine) {
        $("#artist-info ." + nickname + "-links").append(("<li><a href='" + magazine + "' target='blank'>") + "<img src='//d17vwh530ty7de.cloudfront.net/read.gif' /></a>" + ("<a href='" + magazine + "' target='blank'>RBMA Feature</a></li>"));
      }
      if (website) {
        return $("#artist-info ." + nickname + "-links").append(("<li><a href='" + website + "' target='blank'>") + "<img src='//d17vwh530ty7de.cloudfront.net/www.svg' /></a>" + ("<a href='" + website + "' target='blank'>On The Web</a></li>"));
      }
    };
    setUpBinds = function() {
      var artistName, castList, nextArtist, prevArtist;
      artistName = $('.artist-list ul a');
      castList = $('.artist-list ul');
      nextArtist = $('#next-artist');
      prevArtist = $('#prev-artist');
      artistName.bind('mouseenter', function() {
        return getPics($(this));
      });
      artistName.bind('mouseleave', function() {
        return resetPics($(this));
      });
      artistName.bind('click', function() {
        return goToArtist($(this), artistName);
      });
      nextArtist.bind('click', function() {
        return goToNext();
      });
      return prevArtist.bind('click', function() {
        return goToPrev();
      });
    };
    getPics = function(elem) {
      var name, pic;
      name = elem.data('name');
      pic = elem.data('pic');
      $('.artist-images').css({
        display: 'block'
      });
      return setupPics(pic);
    };
    setupPics = function(pic) {
      return $('.artist-images img').each(function() {
        $(this).addClass('hidden');
        if ($(this).hasClass(pic)) {
          $(this).removeClass('hidden');
          return $(this).transition({
            width: '101%'
          }, 900);
        }
      });
    };
    resetPics = function(elem) {
      $('.artist-images img').each(function() {
        $(this).addClass('hidden');
        return $(this).css({
          width: '100%'
        });
      });
      return $('.artist-images').hide();
    };
    goToArtist = function(artist, list) {
      var name, nextArtist, nextId, nextPos, pic, prevArtist, prevId, prevPos;
      currentPos = list.index(artist);
      currentPos++;
      nextPos = currentPos + 1;
      prevPos = currentPos - 1;
      name = artist.data('name');
      pic = artist.data('pic');
      nextArtist = $("#artist").find("ul :nth-child(" + nextPos + ")").data('name');
      nextId = $("#artist").find("ul :nth-child(" + nextPos + ")").data('pic');
      prevArtist = $("#artist").find("ul :nth-child(" + prevPos + ")").data('name');
      prevId = $("#artist").find("ul :nth-child(" + prevPos + ")").data('pic');
      $('#next-artist').removeClass().addClass(nextId);
      $('#prev-artist').removeClass().addClass(prevId);
      $('#artist-info').find('.assets img').empty();
      addInfo(name, pic);
      $('#artist-info').transition({
        left: 0
      }, 500, "ease", function() {
        return $('#go-home').fadeIn(500);
      });
      updateNextArtistLink(nextId, currentPos);
      return currentPos;
    };
    addInfo = function(name, pic) {
      var artistBox, links;
      artistBox = $('#artist-info');
      links = $('#artist-info').find('.links ul');
      artistBox.find('.insert-name').text(name);
      artistBox.find('.exit').removeClass('hidden');
      artistBox.find('.assets img').attr("src", "//d17vwh530ty7de.cloudfront.net/artist/" + pic + ".jpg");
      links.each(function() {
        $(this).css({
          display: 'none'
        });
        $(this).addClass('hidden');
        if ($(this).hasClass("" + pic + "-links")) {
          $(this).removeClass('hidden');
          return $(this).css({
            display: 'block'
          });
        }
      });
      return artistBox.find('p').each(function() {
        $(this).addClass('hidden');
        if ($(this).hasClass("" + pic + "-bio")) {
          return $(this).removeClass('hidden');
        }
      });
    };
    updateNextArtistLink = function(next, currentPos) {
      return $('#next-artist').removeClass().addClass(next);
    };
    goToNext = function() {
      var artist, artistLength, nextId, nextName, ogId, ogName;
      artist = $('#artist').find('.artist-list ul a');
      artistLength = artist.length;
      if (currentPos < artistLength) {
        ogId = $("#artist").find("ul :nth-child(" + currentPos + ")").data('pic');
        ogName = $("#artist").find("ul :nth-child(" + currentPos + ")").data('name');
        nextId = $("#artist").find("ul :nth-child(" + (currentPos + 1) + ")").data('pic');
        nextName = $("#artist").find("ul :nth-child(" + (currentPos + 1) + ")").data('name');
      } else {
        ogId = $("#artist").find("ul :nth-child(0)").data('pic');
        ogName = $("#artist").find("ul :nth-child(0)").data('name');
        nextId = $("#artist").find("ul :nth-child(1)").data('pic');
        nextName = $("#artist").find("ul :nth-child(1)").data('name');
        currentPos = 0;
      }
      addInfo(nextName, nextId);
      updateNextArtistLink(nextId);
      return currentPos++;
    };
    goToPrev = function() {
      var artist, artistLength, ogId, ogName, prevId, prevName;
      artist = $('#artist').find('.artist-list ul a');
      artistLength = artist.length;
      if (currentPos > 1) {
        ogId = $("#artist").find("ul :nth-child(" + currentPos + ")").data('pic');
        ogName = $("#artist").find("ul :nth-child(" + currentPos + ")").data('name');
        prevId = $("#artist").find("ul :nth-child(" + (currentPos - 1) + ")").data('pic');
        prevName = $("#artist").find("ul :nth-child(" + (currentPos - 1) + ")").data('name');
      } else {
        prevId = $("#artist").find("ul :nth-child(" + artistLength + ")").data('pic');
        prevName = $("#artist").find("ul :nth-child(" + artistLength + ")").data('name');
        currentPos = artistLength + 1;
      }
      addInfo(prevName, prevId);
      updateNextArtistLink(prevId);
      return currentPos--;
    };
    return getArtistInfo();
  });

}).call(this);
